# Generated by Django 4.1.9 on 2023-06-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("device_tracker", "0003_devicelocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicelocation",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="device_tracker.device",
            ),
        ),
    ]
